#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

rm -rf processor*/
rm -rf dynamicCode/
rm -rf *[0-9]
rm -f log.*

#------------------------------------------------------------------------------
