#!/bin/sh
cd ${0%/*} || exit 1   # run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

OWN_LIB_SRC=$PWD/src

# OF-7
# OWN_LIB_SRC=$OWN_SRC/transportModels/interfaceProperties
# OF-9
# OWN_LIB_SRC=$OWN_SRC/twoPhaseModels/interfaceProperties

export OWN_LIB_SRC
echo $OWN_LIB_SRC

# Compile OpenFOAM libraries and applications
src/Allwmake $targetType $*

# Compile OpenFOAM libraries and applications
#applications/Allwmake $targetType $*
