#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean time directories only

rm -rf dynamicCode/
rm -rf constant/polyMesh
rm -rf *[0-9]*
rm -f log.*

#------------------------------------------------------------------------------
