#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

cp -r\
    0.orig\
    0

runApplication  blockMesh
runApplication  topoSet
runApplication  decomposePar
runParallel     postProcess -func distanceField
# runApplication  postProcess -func distanceField

# runApplication  $application
# runApplication  $application -withFunctionObjects

#------------------------------------------------------------------------------
