#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Clean time directories only

rm -rf processor*/
rm -rf dynamicCode/
rm -rf constant/
rm -rf 0/
rm -f log.*

#------------------------------------------------------------------------------
