#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication  blockMesh
runApplication -a\
    foamDictionary  -entry numberOfSubdomains -set 4 system/decomposeParDict
runApplication -a\
    foamDictionary  -entry method -set scotch system/decomposeParDict
runApplication  decomposePar
runParallel         snappyHexMesh -overwrite
runParallel         extrudeMesh
runParallel         checkMesh -allTopology -allGeometry
runParallel -a\
    foamDictionary constant/polyMesh/boundary -entry entry0/back/type -set empty
runParallel -a\
    foamDictionary constant/polyMesh/boundary -entry entry0/front/type -set empty
runParallel         $application

#------------------------------------------------------------------------------
