#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

functionObjects/Allwmake $targetType $*
# transportModels/Allwmake $targetType $*
twoPhaseModels/Allwmake $targetType $*

#------------------------------------------------------------------------------
